candel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from candels.views import index_view, CandelListView, AboutTemplateView, CandelDetailView, CandelCreateView, CandelUpdateView, CandelDeleteView
from user.views import RegisterView, AuthView
import debug_toolbar
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', CandelListView.as_view()),
    path('about/', AboutTemplateView.as_view()),
    path('candel/<int:pk>/', CandelDetailView.as_view()),
    path('update/<int:pk>/', CandelUpdateView.as_view()),
    path('delete_confirm/<int:pk>/', CandelDeleteView.as_view()),
    path('create/', CandelCreateView.as_view()),

    path('register/', RegisterView.as_view()),
    #path('', index_view),
    path('candels/', index_view),
    path('login/', AuthView.as_view()),
    path('logout/', LogoutView.as_view())
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

candels/models.py
from django.db import models

# Create your models here.
#Контейнерные, формовые, масажные,
class Body(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


# Ароматические и нет
class Flavoring(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class Color(models.Model):
    name = models.CharField(max_length=32)


    def __str__(self):
        return self.name

    def candlname_count(self):
        return CandlName.objects.filter(color=self).count()


    def flavoring_status(self):
        flavors = self.flavoring.count()
        if flavors == 1:
            return 'One flavor'
        elif flavors == 2:
            return 'Two flavors'
        elif flavors >= 3:
            return 'More than three'
        else:
            return 'No Aroma'


class CandlPrices(models.Model):
    name = models.IntegerField()

    def __int__(self):
        return self.name


class CandlName(models.Model):
    name = models.CharField(max_length=32, unique=True)
    body = models.ForeignKey(Body, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='candel', blank=True, null=True)
    flavoring = models.ManyToManyField(Flavoring)
    candlprices = models.OneToOneField(CandlPrices, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


#class Image(models.Model):
 #   img = models.ImageField(upload_to='album')
  #  candl = models.ForeignKey(CandlName, on_delete=models.CASCADE)

class Card(models.Model):
    name = models.TextField()
    candl_name = models.OneToOneField(CandlName, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

user/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser

# Create your models here.
class MyUser(AbstractUser):
    email = models.EmailField(unique=True)

candels/forms.py
from django import forms
from .models import CandlName

class CandelForm(forms.ModelForm):
    class Meta:
        model = CandlName
        fields = '__all__'

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import MyUser


class RegisterForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ('username', 'email', 'password1', 'password2')

candels/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from .models import CandlName
from django.views.generic import ListView, TemplateView, DetailView, \
    CreateView, UpdateView, DeleteView
from .forms import CandelForm

class CandelDeleteView(DeleteView):

    model = CandlName
    template_name = 'candels/delete_confirm.html'
    success_url = '/'
    form_class = CandelForm

class CandelUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'candels.change_candlname'
    model = CandlName
    template_name = 'candels/create.html'
    success_url = '/'
    form_class = CandelForm


class CandelCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'candels.add_candlname'
    model = CandlName
    template_name = 'candels/create.html'
    success_url = '/'
    form_class = CandelForm

class CandelListView(ListView):
    model = CandlName
    template_name = 'candels/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context['contact_info'] = 'тел: 9589484'
        context['about_ass'] = 'gutfmhgfg'
        return context

    def get_queryset(self):
        return CandlName.objects.select_related('body', 'color', 'card')

    def count_flaver(self):
        flavors = CandlName.objects.prefetch_related('flavoring')
        flowerlen = len(flavors)
        return flowerlen

class AboutTemplateView(TemplateView):
    template_name = 'candels/about.html'
# Create your views here.

class CandelDetailView(DetailView):
    model = CandlName
    template_name = 'candels/candel.html'

    def get_queryset(self):
        return CandlName.objects.prefetch_related('flavoring')



def index_view(request):
    # candl_name = CandlName.objects.all()

    candl_name = CandlName.objects.select_related('candel', 'candl__body')
    # select_related - когда ForeignKey
    # prefetch_relate - когда ManyToMany


    context = {
        'candl_name': candl_name,
        'candls_Magaz': 'Свечи'
    }


    if request.method =="POST":
        with open('candels.txt', 'w', encoding='utf-8') as f:
            for candel in candl_name:
                f.write(candel.name + '\n')

    return render(request, 'candels/index.html', context=context)
    # flask
    # return render(request, 'animals/index.html', animals=animals, zoo_name='Три поросенка')
    # return render(request, 'animals/index.html', **context)

user/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from .models import MyUser
from .forms import RegisterForm
from django.contrib.auth.views import LoginView, LogoutView

# Create your views here.
class RegisterView(CreateView):
    model = MyUser
    form_class = RegisterForm
    template_name = 'user/register.html'
    success_url = '/'

class AuthView(LoginView):
    template_name = 'user/login.html'

candels/templates/candels/about.html
{% extends "base.html" %}
{% block title %}
Главная
{% endblock %}
{% block container %}
О нашей работе, наши свечки ручной работы
{% endblock %}

candels/templates/candels/candel.html
{% extends "base.html" %}
{% block title %}
Главная
{% endblock %}
{% block container %}
<h1>{{object.name}}</h1>
<img src="{{object.image.url}}" class="img-fluid" alt="..." width="500px">
<p><b>Цвет: </b>{{object.color.name }}</p>
<p><b>Форма: </b><i>{{ object.body.name }}</i></p>
<p><b>Ароматизатор: </b>
    {% for v in object.flavoring.all %}
    <i>{{ v.name }},</i>
    {% endfor %}
</p>
<a><b>Описание: </b>{{ object.card.name }}</a>

{% endblock %}

candels/templates/candels/create.html
{% extends "base.html" %}
{% block title %}
Создание свечки
{% endblock %}
{% block container %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Сохранить</button>
</form>
{% endblock %}

candels/templates/candels/delete_confirm.html
{% extends "base.html" %}
{% block title %}
Создание свечки
{% endblock %}
{% block container %}
<h1>{{object.name}}</h1>
<img src="{{object.image.url}}" class="img-fluid" width="400px">

<form method="post">
    <button type="submit" class="btn btn-danger">Удалить</button>
</form>
{% endblock %}

candels/templates/candels/index.html
{% extends "base.html" %}
{% block title %}
Главная
{% endblock %}
{% block container %}
<h1>{{candls_Magaz}}</h1>
<ul class="list-group">
    {% for item in object_list%}
    <div class="shadow p-3 mb-4 bg-body rounded">
    <div class="d-flex position-relative">
        <img src="{{item.image.url}}" class="flex-shrink-0 me-3" alt="..." width="300">
        <div>
            <h5><a href="/candel/{{item.pk}}" class="mt-0" >{{item.name}}</a></h5>
            <p>Цвет: <i>{{item.color.name }}</i></p>
            <p>Форма: <i>{{ item.body.name }}</i></p>

            <p>Ароматизатор: <i>{{ item.flavoring.name }}</i></p>
            <a>Описание: <i>{{ item.card }}</i></a>
            <a href="/update/{{item.pk}}" class="btn btn-primary">Изменить</a>
            <a href="/delete_confirm/{{item.pk}}" class="btn btn-primary">Удалить</a>
            <a href="/create/" class="btn btn-primary">Создать</a>
        </div>
    </div>
    </div>
    {% endfor %}

    <hr>
    <form method="post">
        {% csrf_token %}
        {% if user.is_authenticated %}
        <a href="/create/" class="btn btn-primary">Создать</a>
        {% endif %}
    </form>
</ul>
<hr>
{% endblock %}

templates/base.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel = "stylesheet">
</head>
<body>
<div class="container" style="background-color: #ffecda;">
    <nav  class="navbar navbar-expand-lg navbar-light" style="background-color: #d4a5a5;">
        <div class="container-fluid bg-gradient" >
            <a class="navbar-brand" href="/">Candle Agent</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/about/">О нас</a>
                    </li>
                    <li class="nav-link">{{ contact_info }}</li>

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Добро пожаловать {{user.username}}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/logout/">Выход</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/register/">Зарегистрироваться</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/login/">Вход</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block container %}
    {% endblock %}
    {{ about_ass }}
</div>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

user/templates/user/login.html
{% extends "base.html" %}
{% block title %}
Регистрация
{% endblock %}
{% block container %}


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_username" class="form-label">Имя пользователя:</label>
        <input type="text" class="form-control" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
    </div>
    <div class="mb-3">
        <label for="id_password" class="form-label">Пароль:</label>
        <input class="form-control" type="password" name="password" autocomplete="current-password" required="" id="id_password">
    </div>
    <button class="btn btn-primary" type="submit">Зарегистрироватся</button>
</form>
{% endblock %}

user/templates/user/register.html
{% extends "base.html" %}
{% block title %}
Регистрация
{% endblock %}
{% block container %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
        <label for="id_username" class="form-label">Имя пользователя:</label>
        <input type="text" class="form-control" name="username" maxlength="150" autofocus="" required="" id="id_username">
        <span class="helptext">Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
        </span>
    </p>
    <p>
        <label for="id_email" class="form-label">Email:</label>
        <input type="email" class="form-control" name="email" maxlength="254" required="" id="id_email">
    </p>
    <p>
        <label for="id_password1" class="form-label">Пароль:</label>
        <input type="password" class="form-control" name="password1" autocomplete="new-password" required="" id="id_password1">
        <span class="helptext"></span>
    </p>
    <p>
        <ul>
            <li>
                Пароль не должен быть слишком похож на другую вашу личную информацию.
            </li>
            <li>
                Ваш пароль должен содержать как минимум 8 символов.
            </li>
            <li>
                Такой пароль часто используется.
            </li>
            <li>
                Пароль не может состоять только из цифр.
            </li>
        </ul>
    </p>
    <p>
        <label for="id_password2" class="form-label">Подтверждение пароля:</label>
        <input type="password" class="form-control" name="password2" autocomplete="new-password" required="" id="id_password2">
        <span class="helptext">Для подтверждения введите, пожалуйста, пароль ещё раз.</span>

    </p>
    <button class="btn btn-primary" type="submit">Зарегистрироватся</button>
</form>

{% endblock %}